const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../static/app.js'),'utf8');
const previous={timestamp:'2026-10-09T10:00:00Z',event:'hit',session_id:'old',state:{completed_players:['001'],active_player:'002',hit_progress:2,ticket_dispensed:false}};
const startup={timestamp:'2026-10-09T11:00:00Z',event:'startup',session_id:'new',state:{completed_players:[],active_player:null,hit_progress:0}};
async function run(fail=false,cancel=false){const calls=[],elements=new Map();const context=vm.createContext({console,AbortSignal,URLSearchParams,setInterval,clearInterval,setTimeout:(f)=>{f();},fetch:()=>new Promise(()=>{}),document:{querySelector(s){if(!elements.has(s))elements.set(s,{});return elements.get(s)},querySelectorAll(){return []}},event:previous,events:[previous,startup],allow:!cancel,next:async(i,path,body)=>{calls.push({path,body});if(path==='/game/restore'&&fail)return {ok:false,status:400,data:{error:'Invalid state'}};return {ok:true,status:body===undefined?200:202,data:body===undefined?{status:'DONE',active_player:'002'}:{id:'op'}}}});
vm.runInContext(source,context);assert.equal(vm.runInContext('chooseRestoreEvent(events).session_id',context),'old');assert.equal(vm.runInContext('restorePayload(event.state).hit_progress',context),2);assert.throws(()=>vm.runInContext("restorePayload({completed_players:['999']})",context));
vm.runInContext("selected=0;models=[{restoreChoice:event}];cabinets=[{name:'Test'}];confirmControl=async()=>allow;request=next;pollState=async()=>{};renderRestoreHistory=()=>{};",context);
await vm.runInContext('restoreSavedGame()',context);return {calls,message:elements.get('#activity')?.textContent};}
(async()=>{const success=await run();assert.deepEqual(success.calls.filter(c=>c.body!==undefined).map(c=>c.path),['/maintenance','/game/restore','/resume']);assert.equal(success.calls[2].body.state.active_player,'002');assert.match(success.message,/restored/);const failure=await run(true);assert.deepEqual(failure.calls.filter(c=>c.body!==undefined).map(c=>c.path),['/maintenance','/game/restore']);assert.match(failure.message,/Restore stopped/);assert.equal((await run(false,true)).calls.length,0);console.log('Restore selection, validation, ordered workflow, failure stop, and cancellation checks passed');})().catch(e=>{console.error(e);process.exitCode=1});
